<a href="https://colab.research.google.com/github/ricardo-kowalski/notebooks/blob/master/i2a2_deep_learning_lista1_ex18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#importa as bibliotecas do tensorflow e numpy
import numpy as np
import tensorflow as tf

In [0]:
#inicia uma sessão no tensorflow
sess = tf.Session()

In [3]:
#define uma função que mostra o tipo e valor de uma entrada, 
# após isso atribui à variável 'hello' uma string do tipo constant (cria-se um tensor)
# chama a função print_tf, porém as informações desejadas não aparecem 
# pois a variavel 'hello' apesar de declarada não foi inicializada
def print_tf(x):
    print("TIPO: \n %s" % (type(x)))
    print("Valor: \n %s" % (x))
hello = tf.constant("www.deeplearningbrasil.com.br")
print_tf(hello)

TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("Const:0", shape=(), dtype=string)


In [4]:
#atribui-se à variável 'hello_out' a compilação da variável 'hello'
#chama-se novamente a função print_tf dessa vez utilizando a variável anterior
#que agora é capaz de compilar a sessão
hello_out = sess.run(hello)
print_tf(hello_out)

TIPO: 
 <class 'bytes'>
Valor: 
 b'www.deeplearningbrasil.com.br'


In [5]:
#inicializando dois tensores do tipo float
#novamente a função print_tf apenas fornece informações sobre
#as constantes declaradas e não seus argumentos
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("Const_1:0", shape=(), dtype=float32)
TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("Const_2:0", shape=(), dtype=float32)


In [6]:
#rodando a sessão das constantes declaradas anteriormente
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)

TIPO: 
 <class 'numpy.float32'>
Valor: 
 1.5
TIPO: 
 <class 'numpy.float32'>
Valor: 
 2.5


In [7]:
#declarando uma soma das constantes a e b utilizando o operador soma tf.add
a_plus_b = tf.add(a, b)
print_tf(a_plus_b)

TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("Add:0", shape=(), dtype=float32)


In [8]:
#compilando a operação 
a_plus_b_out = sess.run(a_plus_b)
print_tf(a_plus_b_out)

TIPO: 
 <class 'numpy.float32'>
Valor: 
 4.0


In [9]:
'''
#tf.mul não é um operador reconhecido, o código refeito está logo abaixo
a_mul_b = tf.mul(a, b)
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)
'''
#declarando e imprimindo uma multiplicação das constantes a e b 
#utilizando o operador multiply tf.add
a_mul_b = tf.multiply(a, b)
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)

TIPO: 
 <class 'numpy.float32'>
Valor: 
 3.75


In [10]:
#declarando um segundo tipo de dado denominado variable que diferentemente
#da utilização usual tem aqui como objetivo a inserção de parametros treinaveis em um grafo
weight = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight)

Instructions for updating:
Colocations handled automatically by placer.
TIPO: 
 <class 'tensorflow.python.ops.variables.RefVariable'>
Valor: 
 <tf.Variable 'Variable:0' shape=(5, 2) dtype=float32_ref>


In [11]:
#como anteriormente compila-se a sessão da variável declarada anteriormente, porém ocorre um 
#erro pois o tensorflow requer que sejam inicializadas as variáveis globais antes de sua copilação
weight_out = sess.run(weight)
print_tf(weight_out)

FailedPreconditionError: ignored

In [12]:
#aqui é então inicializado a utilização das variáveis globais no tensorflow e a sessão à roda 
init = tf.initialize_all_variables()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [13]:
#finalmente é possível compilar a variável weight e imprimir seu conteúdo
weight_out = sess.run(weight)
print_tf(weight_out)
print ("INITIALIZING ALL VARIALBES")

TIPO: 
 <class 'numpy.ndarray'>
Valor: 
 [[ 0.07275321  0.10569952]
 [ 0.14030723  0.01166498]
 [-0.04998266 -0.03843571]
 [ 0.08080753 -0.11734322]
 [-0.01281253 -0.05944102]]
INITIALIZING ALL VARIALBES


In [14]:
#aqui é declarado um terceiro tipo básico do tensorflow denominado placeholder, uma variável a qual
#atribuiremos posteriormente algum conteúdo, nesse caso está apenas indicado que será do tipo float32 
#e terá 5 colunas e qualquer número de linhas
x = tf.placeholder(tf.float32, [None, 5])
print_tf(x)

TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


In [15]:
#declara-se uma multiplicação matricial entre o placeholder x e a variable weight
oper = tf.matmul(x, weight)
print_tf(oper)

TIPO: 
 <class 'tensorflow.python.framework.ops.Tensor'>
Valor: 
 Tensor("MatMul:0", shape=(?, 2), dtype=float32)


In [16]:
#cria-se uma matriz aleatória de 1 linha e 5 colunas, alimenta-se x com a matriz data utilizando
#utilizando a função feed_dict e opera-se a multiplicação matricial definida em oper
data = np.random.rand(1, 5)
print(data)    #mostra a matriz data gerada (adicionado por mim)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

[[0.26166865 0.51379257 0.73782967 0.3958285  0.37717234]]
TIPO: 
 <class 'numpy.ndarray'>
Valor: 
 [[ 0.08140074 -0.06357468]]


In [17]:
#gera-se uma matriz de tamanho 2 por 5 que alimentará x e compila-se a sessão oper
data = np.random.rand(2, 5)
print(data)    #mostra a matriz data gerada (adicionado por mim)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

[[0.51132815 0.91805416 0.55328114 0.32284239 0.85699104]
 [0.38420636 0.71546419 0.84368989 0.1298254  0.41581093]]
TIPO: 
 <class 'numpy.ndarray'>
Valor: 
 [[ 0.15346381 -0.04533331]
 [ 0.09133045 -0.02342187]]
